apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: convert-workflow-to-template
  title: Convert serverless workflow to a template
  description: Create a software template out of an existing serverless workflow.
  tags:
    - orchestrator

spec:
  owner: red-hat-developer-hub-authors
  system: red-hat-developer-hub
  type: service

  # matches workflow's dataInputSchema
  parameters:
    - title: Provide inputs
      required:
        - workflow_id
      properties:
        workflow_id:
          title: Workflow ID
          type: string
          ui:autofocus: true

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com
        pluginLocation:
          type: string
          title: Where to publish this new plugin?
          ui:widget: radio
          default: Create a new repository within the specified organization
          enum:
            - Submit a pull request to the same repository
            - Create a new repository within the specified organization
      dependencies:
        pluginLocation:
          allOf:
            - if:
                properties:
                  pluginLocation:
                    const: Submit a pull request to the same repository
              then:
                properties:
                  branchName:
                    title: Branch Name
                    type: string
                    description: The name for the branch
                    default: ''
                  targetBranchName:
                    title: Target Branch Name
                    type: string
                    description: The target branch name of the merge request
                    default: ''
                required:
                  - branchName
                  - targetBranchName
  steps:
    - id: workflow_params
      name: Retrieve workflow parameters
      action: orchestrator:workflow:get_params
      input:
        workflow_id: ${{ parameters.workflow_id }}
        indent: 4 # conforms indentation of the template yaml for the "parameters" property

    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          workflow_id: ${{ parameters.workflow_id }}
          title: ${{ steps.workflow_params.output.title }}
          description: ${{ steps.workflow_params.output.description }}
          parameters: ${{ steps.workflow_params.output.parameters }}
          repoUrl: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}
          repoName: ${{ (parameters.repoUrl | parseRepoUrl).repo }}
          orgName: ${{ (parameters.repoUrl | parseRepoUrl).owner }}

    # GitHub: This step publishes the contents of the working directory to GitHub if it is a new repository.
    - id: publishGithubRepo
      name: Publish the template in a new GitHub repository
      if: ${{ (parameters.repoUrl | parseRepoUrl).host === 'github.com' and parameters.pluginLocation === 'Create a new repository within the specified organization' }}
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is the template for the ${{ parameters.workflow_id }} workflow.
        repoUrl: ${{ parameters.repoUrl }}
        sourcePath: templates/${{parameters.workflow_id}}

    # GitHub: This step creates a pull request with the contents of the working directory.
    - id: publishGithub
      name: Create GitHub pull request with the template
      if: ${{ (parameters.repoUrl | parseRepoUrl).host === 'github.com' and parameters.pluginLocation  === 'Submit a pull request to the same repository' }}
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}
        branchName: ${{ parameters.branchName }}
        targetBranchName: ${{ parameters.targetBranchName }}
        title: Create template ${{ parameters.workflow_id }}
        description: This pull request creates template for running a workflow

    # GitLab: This step publishes the contents of the working directory to a new repository.
    - id: publishGitlabRepo
      name: Publish the template in a new GitLab repository
      action: publish:gitlab
      if: ${{ (parameters.repoUrl | parseRepoUrl).host === 'gitlab.com' and parameters.pluginLocation === 'Create a new repository within the specified organization' }}
      input:
        allowedHosts: ['gitlab.com']
        description: This is the template for the ${{ parameters.workflow_id }} workflow.
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    # GitLab: This step creates a pull request with the contents of the working directory.
    - id: publishGitlab
      name: Create GitLab merge request with the template
      action: publish:gitlab:merge-request
      if: ${{ (parameters.repoUrl | parseRepoUrl).host === 'gitlab.com' and parameters.pluginLocation === 'Submit a pull request to the same repository' }}
      input:
        allowedHosts: ['gitlab.com']
        repoUrl: ${{ parameters.repoUrl }}
        branchName: ${{ parameters.branchName }}
        targetBranchName: ${{ parameters.targetBranchName }}
        title: Create template ${{ parameters.workflow_id }}
        description: This pull request creates template for running a workflow

  output:
    links:
      - title: View template repository
        url: ${{ steps.publishGithubRepo.output.remoteUrl }}
      - title: View template repository
        url: ${{ steps.publishGitlabRepo.output.remoteUrl }}
      - title: View pull request with the template
        url: ${{ steps.publishGithub.output.remoteUrl }}
      - title: View merge request with the template
        url: ${{ steps.publishGitlab.output.mergeRequestUrl }}
