apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: greet
  title: Greeting
  description: Greeting workflow
  annotations:
    orchestrator.io/workflows: '["yamlgreet"]'
  tags:
    - orchestrator
spec:
  owner: red-hat-developer-hub-authors
  system: red-hat-developer-hub
  type: service

  parameters:
    - title: Choose Target Entity
      properties:
        target_entity:
          title: Target Entity for the workflow run
          description: Select an entity from the catalog
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: Component
    - title: Provide workflow inputs
      required:
        - language
      properties:
        language:
          title: Language
          type: string
          ui:autofocus: true
          enum:
            - 'English'
            - 'Spanish'
          default: 'English'
        name:
          title: Name
          type: string
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'

  steps:
    - id: runWorkflow
      name: Run workflow
      action: orchestrator:workflow:run
      input:
        workflow_id: yamlgreet
        target_entity: ${{ parameters.target_entity }}
        parameters: # matches workflow's dataInputSchema
          language: ${{ parameters.language }}
          name: ${{ parameters.name }}

  output:
    links:
      - title: Open workflow run
        url: ${{ steps.runWorkflow.output.instanceUrl }}
