apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-collections
  description: A collection of marketplace plugin collections
spec:
  targets:
    - ./collections/featured.yaml
    - ./collections/kubernetes.yaml
