apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: example-python-template
  title: Example Python Template
  description: A template for creating a new Python service — no time-saved annotation set
  tags:
    - python
    - recommended
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['fetch-base'].output.entityRef }}
