sonar.cpd.exclusions=**/generated/docs/html/index.html, workspaces/orchestrator/plugins/orchestrator-backend-module-loki/src/workflowLogsProviders/LokiProvider.ts, workspaces/*/packages/app/**, workspaces/*/packages/backend/**, **/*.test.*, **/translations/*.ts, **/__fixtures__/*, **/playwright.config.ts


