# NOTICE: In our internal Red Hat DevHub instance this groups are automatically imported due Rover/LDAP.
# This is duplication is for the purpose of using this groups in another test or public Backstage instance.
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rhdh-team
spec:
  type: team
  children: [rhdh-core-team, rhdh-dynamic-plugin-team, rhdh-ui-team]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rhdh-core-team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rhdh-dynamic-plugin-team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rhdh-ui-team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rhtap-team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: orchestrator-team
spec:
  type: team
  children: []
