apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-catalog-backend-module-keycloak
  namespace: extensions-plugin-demo
  title: '@backstage-community/plugin-catalog-backend-module-keycloak'
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-catalog-backend-module-keycloak-dynamic
  tags: []
spec:
  packageName: '@backstage-community/plugin-catalog-backend-module-keycloak'
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic
  version: 3.5.1
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.35.1
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
    - backstage-community-keycloak-catalog-module
  appConfigExamples:
    - title: Default configuration
      content:
        catalog:
          providers:
            keycloakOrg:
              default:
                baseUrl: ${KEYCLOAK_BASE_URL}
                loginRealm: ${KEYCLOAK_LOGIN_REALM}
                realm: ${KEYCLOAK_REALM}
                clientId: ${KEYCLOAK_CLIENT_ID}
                clientSecret: ${KEYCLOAK_CLIENT_SECRET}
                schedule:
                  frequency:
                    minutes: 60
                  initialDelay:
                    seconds: 15
                  timeout:
                    minutes: 50
