apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-quay
  namespace: extensions-plugin-demo
  title: '@backstage-community/plugin-quay'
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-quay
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-quay
  tags: []
spec:
  packageName: '@backstage-community/plugin-quay'
  dynamicArtifact: '@backstage-community/plugin-quay'
  integrity: sha512-qaZgy2lV28qlwsNnympCUbkewYCqXxLmXQXr3WWpS7gREWj4YBpytU/hQnDnqxAnQ+dQB/9U/rPdGJnLLAOB3w==
  version: 1.18.1
  backstage:
    role: frontend-plugin
    supportedVersions: 1.35.1
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
    - backstage-community-quaysd
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-quay:
              mountPoints:
                - mountPoint: entity.page.image-registry/cards
                  importName: QuayPage
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      anyOf:
                        - isQuayAvailable
