apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-topology
  namespace: extensions-plugin-demo
  title: '@backstage-community/plugin-topology'
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/janus-idp/backstage-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-topology
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-topology
  tags: []
spec:
  packageName: '@backstage-community/plugin-topology'
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-topology
  version: 1.32.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.35.1
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
    - topology
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-topology:
              mountPoints:
                - mountPoint: entity.page.topology/cards
                  importName: TopologyPage
                  config:
                    layout:
                      gridColumn: 1 / -1
                      height: 75vh
                    if:
                      anyOf:
                        - hasAnnotation: backstage.io/kubernetes-id
                        - hasAnnotation: backstage.io/kubernetes-namespace
