apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: developer-lightspeed
  title: Developer Lightspeed plugin
  description: |
    Red Hat Developer Lightspeed for Red Hat Developer Hub is a virtual assistant powered by generative AI that offers in-depth insights into RHDH, including its wide range of capabilities. You can interact with this assistant to explore and learn more about RHDH in greater detail.
  tags:
    - backstage
    - rhdh
    - plugin
    - ai
  annotations:
    github.com/project-slug: redhat-developer/rhdh-plugins
    github.com/team-slug: redhat-developer/rhdh-plugins-contributers
    sonarqube.org/project-key: redhat-developer_rhdh-plugins
    jira/project-key: RHIDP
    jira/component: Lightspeed
spec:
  type: backstage-plugin
  lifecycle: active
  owner: rhdh-team
  system: rhdh
  subcomponentOf: rhdh-plugins
