# yaml-language-server: $schema=../../json-schema/collections.json
apiVersion: marketplace.backstage.io/v1alpha1
kind: PluginCollection
metadata:
  name: disabled-featured
  title: Featured Plugins
  description: A set of great plugins! :)
spec:
  type: curated
  plugins:
    - quay
    - 3scale
    - tekton
    - topology
