---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: x2a-admin-group
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  annotations:
    # example for Bitbucket usernameMatchingUserEntityAnnotation resolver
    # the Bitbucket adds "-admin" to my username (based on role)
    bitbucket.org/username: mareklibra-admin
  name: mareklibra
spec:
  profile:
    displayName: Marek Libra
    email: foo@bar.com
  memberOf: [x2a-admin-group]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: elai-shalev
spec:
  profile:
    displayName: Elai Shalev
    email: foo@bar.com
  memberOf: []
