apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-scorecards-location

  description: A collection of all the scorecards
spec:
  targets:
    - ./components/all-scorecards-service-different-owner.yaml
    - ./components/all-scorecards.yaml
    - ./components/dependabot-scorecard-only.yaml
    - ./components/github-scorecard-only.yaml
    - ./components/jira-scorecard-only.yaml
    - ./components/no-scorecards.yaml
    - ./components/openssf-scorecard-only.yaml
    - ./components/sonarqube-scorecard-only.yaml
