apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-scorecards
  description: A collection of all the scorecards
spec:
  targets:
    - ./components/dependabot-scorecard-only.yaml
    - ./components/entities.yaml
    - ./components/github-scorecard-only.yaml
    - ./components/jira-scorecard-only.yaml
    - ./components/no-scorecards.yaml
    - ./components/openssf-scorecard-only.yaml
    - ./orgs/guest.yaml