---
# Component with OpenSSF Scorecard
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dependabot-scorecard-only
  annotations:
    github.com/project-slug: alizard0/rhdh-plugins
    #dependabot/title: "Vulnerabilities"
spec:
  type: service
  owner: group:development/guests
  lifecycle: experimental
