---
# Component with Jira Scorecard only
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jira-scorecard-only-service
  annotations:
    jira/project-key: RSPT
spec:
  type: service
  owner: group:development/guests
  lifecycle: production
