apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  annotations:
    github.com/project-slug: ${{ values.organization }}/${{ values.name }}
spec:
  type: other
  owner: ${{ values.organization }}
  lifecycle: unknown
