/*
 * Copyright Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { createTranslationRef } from '@backstage/core-plugin-api/alpha';

/**
 * Messages object containing all English translations.
 * Keys are flattened (dot-notation) to produce a deterministic key order
 * in the API report across different build environments.
 * @public
 */
export const x2aPluginMessages = {
  sidebar: {
    x2a: {
      title: 'Conversion Hub',
    },
  },
  page: {
    title: 'Conversion Hub',
    subtitle:
      'Initiate and track the asynchronous conversion of legacy infrastructure automation into production-ready Ansible Playbooks.',
  },
  projectPage: {
    title: 'Project',
    deleteProject: 'Delete',
    actionsTooltip: 'Click to open the menu for project actions',
    deleteError: 'Failed to delete project',
    deleteConfirm: {
      title: 'Delete project "{{name}}"?',
      message:
        'This project, all its modules and jobs will be permanently deleted. This action cannot be undone. The artifacts persisted in the target repository will be preserved.',
      cancel: 'Cancel',
      confirm: 'Delete',
    },
  },
  projectTable: {
    deleteError: 'Failed to delete project',
  },
  projectDetailsCard: {
    title: 'Project Details',
    name: 'Name',
    abbreviation: 'Abbreviation',
    status: 'Status',
    createdBy: 'Created By',
    description: 'Description',
    sourceRepo: 'Source Repository',
    targetRepo: 'Target Repository',
  },
  projectModulesCard: {
    title: 'Modules ({{count}})',
    noModules: 'No modules found yet...',
    toReview: 'review',
    published: 'published',
  },
  initPhaseCard: {
    title: 'Discovery Phase',
  },
  modulePage: {
    title: 'Module Details',
    artifacts: {
      title: 'Artifacts to review',
      migration_plan: 'Overall project migration plan',
      module_migration_plan: 'Module plan by analysis',
      migrated_sources: 'Migrated Sources',
      ansible_project: 'AAP Project',
      description:
        'These artifacts are generated by the conversion process and are available for review.',
    },
    phases: {
      title: 'Migration Phases',
      id: 'ID',
      duration: 'Duration',
      k8sJobName: 'Kubernetes Job Name',
      startedAt: 'Started At',
      status: 'Status',
      errorDetails: 'Error Details',
      statuses: {
        notStarted: 'Not Started',
        pending: 'Pending',
        running: 'Running',
        success: 'Success',
        error: 'Error',
        cancelled: 'Cancelled',
      },
      resyncMigrationPlanInstructions:
        'Resync module list to match the migration plan.',
      reanalyzeInstructions:
        'The module migration plan is already present. In case the overall project migration plan has been updated, retrigger the analysis to reflect the changes.',
      rerunAnalyze: 'Recreate the module migration plan',
      analyzeInstructions:
        'Before running the analysis, review the overall project migration plan first. Its content will drive the analysis of the module.',
      runAnalyze: 'Create module migration plan',
      migrateInstructions:
        'Before running the migration, review the module migration plan. The migration process will convert the source code to Ansible based on the plan.',
      runMigrate: 'Migrate module sources',
      remigrateInstructions:
        'The migrated sources are already present. Retrigger the migration to recreate the converted Ansible code.',
      rerunMigrate: 'Recreate migrated sources',
      publishInstructions:
        'Before publishing, review the migrated sources. The publish process will commit the converted code to the target repository.',
      runPublish: 'Publish to target repository',
      republishInstructions:
        'The module has already been published. Retrigger the publish to update the target repository.',
      rerunPublish: 'Republish to target repository',
      cancel: 'Cancel',
      runError: 'Failed to run phase for module',
      cancelError: 'Failed to cancel phase for module',
      commitId: 'Last Commit ID',
      viewLog: 'View Log',
      hideLog: 'Hide Log',
      noLogsAvailable: 'No logs available yet...',
      logWaitingForStream: 'Waiting for log output from the cluster...',
      telemetry: {
        title: 'Telemetry',
        noTelemetryAvailable: 'No telemetry available',
        agentName: 'Agent Name',
        duration: 'Duration',
        inputTokens: 'Input Tokens',
        outputTokens: 'Output Tokens',
        toolCalls: 'Count of tool calls',
      },
    },
  },
  table: {
    columns: {
      name: 'Name',
      status: 'Status',
      statusSortDisabledTooltip:
        'Sorting by status is not available when the project count exceeds {{threshold}}',
      sourceRepo: 'Source Repository',
      targetRepo: 'Target Repository',
      createdAt: 'Created At',
    },
    actions: {
      deleteProject: 'Delete project',
      retriggerInit: 'Retrigger project init phase',
      expandAll: 'Expand all rows',
      collapseAll: 'Collapse all rows',
      expandRow: 'Expand row',
      collapseRow: 'Collapse row',
    },
    projectsCount: 'Projects ({{count}})',
  },
  project: {
    description: 'Description',
    id: 'ID',
    abbreviation: 'Abbreviation',
    createdBy: 'Owned By',
    statuses: {
      none: '-',
      created: 'Created',
      initializing: 'Initializing',
      initialized: 'Initialized',
      inProgress: 'In progress',
      completed: 'Completed',
      failed: 'Failed',
    },
    noModules: 'No modules found yet...',
  },
  common: {
    newProject: 'New Project',
  },
  emptyPage: {
    noConversionInitiatedYet: 'No conversion initiated yet',
    noConversionInitiatedYetDescription:
      'Initiate and track conversion of legacy infrastructure automation into production-ready Ansible',
    startFirstConversion: 'Start first conversion',
    notAllowedTitle: 'Access denied',
    notAllowedDescription: 'You are not allowed to access conversion projects.',
  },
  bulkRun: {
    projectAction: 'Run all modules',
    globalAction: 'Run all',
    projectPageAction: 'Run all',
    projectConfirm: {
      title: 'Run all modules in "{{name}}" project?',
      message:
        'This will trigger the next migration phase for every module in this project whose current state allows it. Make sure you have all the necessary artifacts in the target repositories reviewed before running this action. Modules that are not eligible will be skipped.',
    },
    globalConfirm: {
      title: 'Run all eligible projects and modules?',
      message:
        'This will trigger the next migration phase for all eligible modules across every project you have write access to, including projects not visible on the current page. Make sure you have all the necessary artifacts in the target repositories reviewed before running this action.',
      messageInitRetrigger:
        'Some projects are eligible for re-running the init phase. Their discovery phase will also be retriggered.',
      noInitEligible:
        'No projects are currently eligible for re-running the init phase.',
      userPromptLabel: 'User prompt for init retrigger (optional)',
      userPromptPlaceholder:
        'If any projects need their init phase retriggered, this prompt will be used to customize the conversion…',
    },
    projectPageConfirm: {
      title: 'Run all modules in "{{name}}"?',
      message:
        'This will trigger the next migration phase for every module in this project whose current state allows it. Make sure you have all the necessary artifacts in the target repositories reviewed before running this action. Modules that are not eligible will be skipped.',
    },
    confirm: 'Run all',
    cancel: 'Cancel',
    errorProject: 'Failed to run modules in project "{{name}}"',
    errorModuleStart:
      'Failed to start phase "{{phase}}" for module "{{moduleName}}"',
    errorGlobal: 'Failed to run bulk operation',
  },
  retriggerInit: {
    confirm: {
      title: 'Retrigger init phase for "{{name}}"?',
      message:
        'This will retrigger the discovery phase for the project, starting a new init job. Any previous init results will be replaced.',
      userPromptLabel: 'User prompt (optional)',
      userPromptPlaceholder:
        'Provide additional instructions for the conversion…',
      confirmButton: 'Retrigger',
    },
    firstTrigger: {
      title: 'Trigger init phase for "{{name}}"?',
      message:
        'When confirmed, the discovery phase for this project will be started. You might be asked for your source and target SCM tokens.',
      userPromptLabel: 'User prompt (optional)',
      userPromptPlaceholder:
        'Provide additional instructions for the conversion…',
      confirmButton: 'Trigger init phase',
    },
    error: 'Failed to retrigger init for project "{{name}}"',
    errorStart: 'Failed to start project init',
  },
  module: {
    phases: {
      init: 'Init',
      none: '-',
      analyze: 'Analyze',
      migrate: 'Migrate',
      publish: 'Publish',
    },
    summary: {
      total: 'Total',
      finished: 'Finished',
      waiting: 'Waiting',
      pending: 'Pending',
      running: 'Running',
      error: 'Error',
      cancelled: 'Cancelled',
      toReview_one: '{{count}} module with artifacts to review',
      toReview_other: '{{count}} modules with artifacts to review',
    },
    actions: {
      runNextPhase: 'Run the next {{phase}} phase',
      cancelPhase: 'Cancel the {{phase}} phase',
      cancelPhaseError: 'Failed to cancel phase for module',
      runNextPhaseError: 'Failed to run next phase for module',
    },
    currentPhase: 'Current Phase',
    lastUpdate: 'Last Update',
    notStarted: 'Not Started',
    name: 'Name',
    status: 'Status',
    sourcePath: 'Source Path',
    artifacts: 'Artifacts',
    statuses: {
      none: '-',
      pending: 'Pending',
      running: 'Running',
      success: 'Success',
      error: 'Error',
      cancelled: 'Cancelled',
    },
  },
  artifact: {
    types: {
      migration_plan: 'Project Migration Plan',
      module_migration_plan: 'Module Migration Plan',
      migrated_sources: 'Migrated Sources',
      project_metadata: 'Project Metadata',
      ansible_project: 'AAP Project',
    },
  },
  time: {
    duration: {
      daysAndHours: '{{days}}d {{hours}}h',
      daysOnly: '{{days}}d',
      hoursAndMinutes: '{{hours}}h {{minutes}}m',
      hoursOnly: '{{hours}}h',
      minutesAndSeconds: '{{minutes}}m {{seconds}}s',
      secondsOnly: '{{seconds}}s',
    },
    ago: {
      daysAndHours: '{{days}}d {{hours}}h ago',
      daysOnly: '{{days}}d ago',
      hoursAndMinutes: '{{hours}}h {{minutes}}m ago',
      hoursOnly: '{{hours}}h ago',
      minutes: '{{minutes}}m ago',
      lessThanMinute: '<1m ago',
    },
    jobTiming: {
      noStartTime: '-',
      running: 'Running for {{duration}}',
      finished: 'Finished {{timeAgo}} (took {{duration}})',
    },
  },
  empty: '-',
};

/**
 * Reference translation for the x2a plugin.
 * Defines all the translation keys used in the plugin.
 * @public
 */
export const x2aPluginTranslationRef = createTranslationRef({
  id: 'plugin.x2a',
  messages: x2aPluginMessages,
});
