/*
 * Copyright Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { createTranslationRef } from '@backstage/core-plugin-api/alpha';

/**
 * Messages object containing all English translations.
 * Keys are flattened (dot-notation) to produce a deterministic key order
 * in the API report across different build environments.
 * @public
 */
export const x2aPluginMessages = {
  sidebar: {
    x2a: {
      title: 'Conversion Hub',
    },
  },
  page: {
    title: 'Conversion Hub',
    subtitle:
      'Initiate and track the asynchronous conversions of Chef files into production-ready Ansible Playbooks.',
  },
  projectPage: {
    title: 'Project',
    deleteProject: 'Delete',
    actionsTooltip: 'Click to open the menu for project actions',
    deleteError: 'Failed to delete project',
    deleteConfirm: {
      title: 'Delete project "{{name}}"?',
      message:
        'This project, all its modules and jobs will be permanently deleted. This action cannot be undone. The artifacts persisted in the target repository will be preserved.',
      cancel: 'Cancel',
      confirm: 'Delete',
    },
  },
  projectTable: {
    deleteError: 'Failed to delete project',
  },
  projectDetailsCard: {
    title: 'Project Details',
    name: 'Name',
    abbreviation: 'Abbreviation',
    status: 'Status',
    createdBy: 'Created By',
    description: 'Description',
    sourceRepo: 'Source Repository',
    targetRepo: 'Target Repository',
  },
  projectModulesCard: {
    title: 'Modules ({{count}})',
    noModules: 'No modules found yet...',
    toReview: 'review',
    published: 'published',
  },
  initPhaseCard: {
    title: 'Discovery Phase',
  },
  modulePage: {
    title: 'Module Details',
    artifacts: {
      title: 'Artifacts to review',
      migration_plan: 'Overall project migration plan',
      module_migration_plan: 'Module plan by analysis',
      migrated_sources: 'Migrated Sources',
      ansible_project: 'AAP Project',
      description:
        'These artifacts are generated by the conversion process and are available for review.',
    },
    phases: {
      title: 'Migration Phases',
      id: 'ID',
      duration: 'Duration',
      k8sJobName: 'Kubernetes Job Name',
      startedAt: 'Started At',
      status: 'Status',
      errorDetails: 'Error Details',
      statuses: {
        notStarted: 'Not Started',
        pending: 'Pending',
        running: 'Running',
        success: 'Success',
        error: 'Error',
      },
      resyncMigrationPlanInstructions:
        'Resync module list to match the migration plan.',
      reanalyzeInstructions:
        'The module migration plan is already present. In case the overall project migration plan has been updated, retrigger the analysis to reflect the changes.',
      rerunAnalyze: 'Recreate the module migration plan',
      analyzeInstructions:
        'Before running the analysis, review the overall project migration plan first, its content will drive the analysis of the module.',
      runAnalyze: 'Create module migration plan',
      migrateInstructions:
        'Before running the migration, review the module migration plan. The migration process will convert the Chef code to Ansible based on the plan.',
      runMigrate: 'Migrate module sources',
      remigrateInstructions:
        'The migrated sources are already present. Retrigger the migration to recreate the converted Ansible code.',
      rerunMigrate: 'Recreate migrated sources',
      publishInstructions:
        'Before publishing, review the migrated sources. The publish process will commit the converted code to the target repository.',
      runPublish: 'Publish to target repository',
      republishInstructions:
        'The module has already been published. Retrigger the publish to update the target repository.',
      rerunPublish: 'Republish to target repository',
      commitId: 'Last Commit ID',
      viewLog: 'View Log',
      hideLog: 'Hide Log',
      noLogsAvailable: 'No logs available yet...',
      telemetry: {
        title: 'Telemetry',
        noTelemetryAvailable: 'No telemetry available',
        agentName: 'Agent Name',
        duration: 'Duration',
        toolCalls: 'Tool Calls',
      },
    },
  },
  table: {
    columns: {
      name: 'Name',
      status: 'Status',
      sourceRepo: 'Source Repository',
      targetRepo: 'Target Repository',
      createdAt: 'Created At',
    },
    actions: {
      deleteProject: 'Delete project',
      expandAll: 'Expand all rows',
      collapseAll: 'Collapse all rows',
      expandRow: 'Expand row',
      collapseRow: 'Collapse row',
    },
    projectsCount: 'Projects ({{count}})',
  },
  project: {
    description: 'Description',
    id: 'ID',
    abbreviation: 'Abbreviation',
    createdBy: 'Owned By',
    statuses: {
      none: '-',
      created: 'Created',
      initializing: 'Initializing',
      initialized: 'Initialized',
      inProgress: 'In progress',
      completed: 'Completed',
      failed: 'Failed',
    },
    noModules: 'No modules found yet...',
  },
  common: {
    newProject: 'New Project',
  },
  emptyPage: {
    noConversionInitiatedYet: 'No conversion initiated yet',
    noConversionInitiatedYetDescription:
      'Initiate and track conversion of Chef files into production-ready Ansible',
    startFirstConversion: 'Start first conversion',
    notAllowedTitle: 'Access denied',
    notAllowedDescription: 'You are not allowed to access conversion projects.',
  },
  module: {
    phases: {
      init: 'Init',
      none: '-',
      analyze: 'Analyze',
      migrate: 'Migrate',
      publish: 'Publish',
    },
    summary: {
      total: 'Total',
      finished: 'Finished',
      waiting: 'Waiting',
      pending: 'Pending',
      running: 'Running',
      error: 'Error',
      toReview_one: '{{count}} module with artifacts to review',
      toReview_other: '{{count}} modules with artifacts to review',
    },
    actions: {
      runNextPhase: 'Run Next Phase',
    },
    currentPhase: 'Current Phase',
    lastUpdate: 'Last Update',
    notStarted: 'Not Started',
    name: 'Name',
    status: 'Status',
    sourcePath: 'Source Path',
    artifacts: 'Artifacts',
    statuses: {
      none: '-',
      pending: 'Pending',
      running: 'Running',
      success: 'Success',
      error: 'Error',
    },
  },
  artifact: {
    types: {
      migration_plan: 'Project Migration Plan',
      module_migration_plan: 'Module Migration Plan',
      migrated_sources: 'Migrated Sources',
      project_metadata: 'Project Metadata',
      ansible_project: 'AAP Project',
    },
  },
  empty: '-',
};

/**
 * Reference translation for the x2a plugin.
 * Defines all the translation keys used in the plugin.
 * @public
 */
export const x2aPluginTranslationRef = createTranslationRef({
  id: 'plugin.x2a',
  messages: x2aPluginMessages,
});
