apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: example-nodejs-template
  title: Example Node.js Template
  description: An example template for the scaffolder that creates a simple Node.js service
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Send a notification
      required:
        - title
        - message
      properties:
        title:
          title: Title
          type: string
          ui:autofocus: true
        message:
          title: Message
          type: string

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Let's notify the user that the template has completed using the Notification action
    - id: notify
      name: Notify
      action: notification:send
      input:
        recipients: entity
        entityRefs:
          - user:development/guest
        title: ${{ parameters.title }}
        info: ${{ parameters.message }}
        severity: 'normal'
