apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: catalog-metadata-scorecard-with-title
  title: Catalog Metadata Scorecard With Title
  annotations:
    scorecard.example: catalog-metadata
spec:
  type: service
  owner: group:development/guests
  lifecycle: production
