apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: catalog-scorecard-with-title
  title: Catalog Scorecard With Title
  annotations:
    scorecard/example: catalog
spec:
  type: service
  owner: group:development/guests
  lifecycle: production
