# yaml-language-server: $schema=../../json-schema/packages.json
kind: Package
apiVersion: marketplace.backstage.io/v1alpha1
metadata:
  name: backstage-community-plugin-tekton
  title: '@backstage-community/plugin-tekton'
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-tekton
  annotations:
    backstage.io/source-location: url
      https://github.com/redhat-developer/rhdh/tree/main/dynamic-plugins/wrappers/backstage-community-plugin-tekton
  tags: []
spec:
  packageName: '@backstage-community/plugin-tekton'
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-tekton
  version: 3.17.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.35.0
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
    - tekton
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-tekton:
              mountPoints:
                - mountPoint: entity.page.ci/cards
                  importName: TektonCI
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - isTektonCIAvailable
