apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-catalog-info
  title: Add catalog-info.yaml to repo
  description: Creates a catalog-info.yaml in the given GitHub repo if it does not exist.

spec:
  owner: user:default/guest
  type: service

  parameters:
    - title: Provide repository details
      required:
        - repoUrl
        - owner
      properties:
        repoUrl:
          type: string
          title: Repository URL (GitHub)
          description: 'e.g. https://github.com/owner/repo'
        owner:
          type: string
          title: Backstage Owner
          description: e.g. user:default/andrienkoaleksandr

  steps:
    - id: fetchRepo
      name: Fetch repository contents
      # Download repository content directly to the the root directory of the working space Scaffolder
      # Notice: fetch:template requires full http/https URL Github address.
      action: fetch:template
      input:
        url: ${{ parameters.repoUrl }}
        revision: ${{ steps.fetchRepo.output.targetBranchName }}
        targetPath: .

    - id: checkCatalogInfo
      name: Read files in workspace root
      action: fs:readdir
      input:
        paths:
          - .

    - id: checkFileExists
      name: Check if catalog-info.yaml exists
      action: roadiehq:utils:jsonata
      input:
        data: ${{ steps.checkCatalogInfo.output.files }}
        expression: '"catalog-info.yaml" in $'

    - id: createCatalogInfo
      name: Create catalog-info.yaml
      if: ${{ steps.checkFileExists.output.result }} === false
      action: roadiehq:utils:fs:write
      input:
        path: ./catalog-info.yaml
        content: |
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            # The component name is taken from the repository name.
            name: ${{ parameters.repoUrl.split('/')[4] }}
            annotations:
              # project-slug has to be in format OWNER_NAME/REPO_NAME
              github.com/project-slug: ${{ parameters.repoUrl.split('.com/')[1] }}
          spec:
            type: other
            lifecycle: unknown
            owner: ${{ parameters.owner }}

    - id: get-default-branch
      name: Get Default Branch
      action: git:get-default-repository-branch
      input:
        repoUrl: ${{ parameters.repoUrl }}

    - id: log-branch
      name: Log Default Branch
      action: debug:log
      input:
        message: 'The default branch is: ${{ steps["get-default-branch"].output.defaultBranch }}'

    - id: publish
      name: Create PR to add catalog-info.yaml
      # Create pull request to add catalog-info.yaml to the repository.
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=${{ parameters.repoUrl.split('/')[4] }}&owner=${{ parameters.repoUrl.split('/')[3] }}
        branchName: add-catalog-info-${{ parameters.repoUrl.split('/')[4] }}
        targetBranchName: ${{ steps['get-default-branch'].output.defaultBranch }}
        title: 'Add catalog-info.yaml'
        description: 'This PR adds a default catalog-info.yaml for Backstage.'
    - id: debug
      name: Debug
      action: debug:log
      input:
        message: 'repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}'
  
    - id: register
      name: Register catalog-info.yaml
      action: catalog:register-with-event
      input:
        # https://github.com/AndrienkoAleksandr/shellImages/tree/master/catalog-info.yaml
        repoContentsUrl: https://github.com/${{ parameters.repoUrl.split('/')[3] }}/${{ parameters.repoUrl.split('/')[4] }}/blob/${{ steps['get-default-branch'].output.defaultBranch }}/catalog-info.yaml
