apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-pr-with-catalog-info
  title: Propose catalog-info.yaml in the pull request
  description: Creates a catalog-info.yaml in the given GitHub repo.

spec:
  owner: user:default/guest
  type: service

  parameters:
    - title: Provide repository details
      required:
        - repoUrl
      properties:
        repoUrl:
          type: string
          title: Repository URL (Backstage format)
          description: 'e.g. github.com?owner=Org&repo=repoName'

  steps:
    - id: parse-query
      name: Parse GitHub Query
      action: roadiehq:utils:jsonata
      input:
        data: ${{ parameters.repoUrl }}
        expression: |
          {
            "owner": $substringAfter($substringBefore($, "&repo="), "?owner="),
            "repo": $substringAfter($, "&repo=")
          }

    - id: get-default-branch
      name: Get Default Branch
      action: git:get-default-repository-branch
      input:
        repoUrl: ${{ parameters.repoUrl }}

    - id: createCatalogInfo
      name: Prepare catalog-info.yaml
      action: roadiehq:utils:fs:write
      input:
        path: ./catalog-info.yaml
        content: |
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: ${{ steps['parse-query'].output.result.repo }}
            annotations:
              github.com/project-slug: ${{ steps['parse-query'].output.result.owner }}/${{ steps['parse-query'].output.result.repo }}
          spec:
            type: other
            lifecycle: unknown
            owner: user:default/test-user

    - id: publish
      name: Create PR to add catalog-info.yaml
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: add-catalog-info-${{ steps['parse-query'].output.result.repo }}
        targetBranchName: ${{ steps['get-default-branch'].output.defaultBranch }}
        title: 'Add catalog-info.yaml'
        description: 'This PR adds a default catalog-info.yaml for Backstage.'

    - id: register
      name: Register catalog-info.yaml
      action: catalog:register
      input:
        optional: true
        repoContentsUrl: https://github.com/${{ steps['parse-query'].output.result.owner }}/${{ steps['parse-query'].output.result.repo }}/blob/${{ steps['get-default-branch'].output.defaultBranch }}/catalog-info.yaml
