apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: get-default-branch-template
  title: Get Default Branch Template
  description: A template to get the default branch of a git repository
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Repository URL
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: get-default-branch
      name: Get Default Branch
      action: git:get-default-repository-branch
      input:
        repoUrl: ${{ parameters.repoUrl }}

    - id: log-branch
      name: Log Default Branch
      action: debug:log
      input:
        message: 'The default branch is: ${{ steps["get-default-branch"].output.defaultBranch }}'

  output:
    defaultBranch: ${{ steps['get-default-branch'].output.defaultBranch }}
