apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: chef-conversion-project-template
  title: Chef-to-Ansible Conversion Project
  description: Initiate a conversion of a Chef cookbook or directory into a new Ansible Playbook repository.
spec:
  type: service

  parameters:
    - title: Job name and description
      required:
        - name
        - abbreviation
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the conversion project
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Description of the project
          ui:widget: textarea
          ui:options:
            rows: 3
        abbreviation:
          title: Abbreviation
          type: string
          default: 'myprj'
          description: Abbreviation of the project to ease the project identification in the target repository.
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
          maxLength: 5
          minLength: 1
    - title: Source and target repositories
      ui:order:
        - sourceRepoUrl
        - sourceRepoBranch
        - areTargeAndSourceRepoShared
        - targetRepoUrl
        - targetRepoBranch
      required:
        - sourceRepoUrl
        - sourceRepoBranch
        - targetRepoBranch
      properties:
        sourceRepoUrl:
          title: Conversion source repository
          description: |
            The Owner should be your GitHub username. The repository name should be a name that already exists in your GitHub account and contains a Chef cookbook or directory to convert.
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: SRC_USER_OAUTH_TOKEN
              #additionalScopes:
              #  github:
              #    - workflow
            allowedHosts:
              - github.com
        sourceRepoBranch:
          title: Conversion source repository branch
          type: string
          description: The branch of the source repository to use for the conversion.
          default: 'main'
        areTargeAndSourceRepoShared:
          title: Use the same repository for target and source
          type: boolean
          description: If checked, the target repository will be the same as the source repository.
          default: true

        # TODO: Replace by https://backstage.io/docs/features/software-templates/writing-templates#the-repository-branch-picker
        targetRepoBranch:
          title: Conversion target repository branch
          type: string
          description: The branch of the target repository to use for the conversion.
          default: 'main'
      dependencies:
        areTargeAndSourceRepoShared:
          allOf:
            - if:
                properties:
                  areTargeAndSourceRepoShared:
                    const: false
              then:
                properties:
                  targetRepoUrl:
                    title: Conversion target repository
                    description: |
                      The Owner should be your GitHub username. The repository name should be a name that already exists in your GitHub account. It will be populated by converted Ansible sources and intermediary artifacts.
                    type: string
                    ui:field: RepoUrlPicker
                    ui:options:
                      requestUserCredentials:
                        secretsKey: TGT_USER_OAUTH_TOKEN
                      allowedHosts:
                        - github.com

    - title: Conversion parameters
      properties:
        userPrompt:
          title: User prompt
          type: string
          description: User prompt for the conversion project initialization phase.
          ui:widget: textarea
          ui:options:
            rows: 3

  steps:
    - id: createProject
      name: Create Project
      action: x2a:project:create
      input:
        name: ${{ parameters.name }}
        description: ${{ parameters.description }}
        abbreviation: ${{ parameters.abbreviation }}
        sourceRepoUrl: ${{ parameters.sourceRepoUrl }}
        sourceRepoBranch: ${{ parameters.sourceRepoBranch }}
        areTargeAndSourceRepoShared: ${{ parameters.areTargeAndSourceRepoShared }}
        targetRepoUrl: ${{ parameters.targetRepoUrl }}
        targetRepoBranch: ${{ parameters.targetRepoBranch }}
        userPrompt: ${{ parameters.userPrompt }}

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Manage the project
        url: ${{ steps.createProject.output.nextUrl }}
