site_name: Extensions Plugin

plugins:
  - techdocs-core

nav:
  - About: index.md
  - Catalog:
      - Entites: catalog/index.md
      - Plugins: catalog/plugins.md
      - Packages: catalog/packages.md
      - Collections: catalog/collections.md
  - Tools:
      - CLI: tools/cli.md
      - JSON schema: tools/json-schema.md
