#!/usr/bin/env bash
# Copyright Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

script_name="${BASH_SOURCE:-$0}"
script_path=$(realpath "$script_name")
script_dir_path=$(dirname "$script_path")
workspace_dir=$(dirname "$script_dir_path")
dynamic_plugins_root_dir="$workspace_dir/dynamic-plugins-root"

REGISTRY_URL="${REGISTRY_URL:-quay.io}"
ORG_ID="${ORG_ID:-dcm-project}"
REPO="${REPO:-dcm-ui}"
VERSION="${VERSION:-}"

function _usage {
  cat <<EOF
Usage:
  $script_name clean
  VERSION=<semver> $script_name [oci|tgz|push]
  VERSION=<semver> $script_name backstage-image [--push]

Environment variables:
  VERSION         Required. The plugin version; also used to tag the container image.
  REGISTRY_URL    Optional. Container registry URL. Default: quay.io
  ORG_ID          Optional. Organization / namespace in the registry. Default: rh-ee-asmasarw
  REPO            Optional. Repository name. Default: dcm

Sub-commands:
  clean             Removes directories generated by this script.
  oci               Builds an OCI artifact containing the DCM dynamic plugins and tags it
                    as \$REGISTRY_URL/\$ORG_ID/\$REPO:\$VERSION. This is the preferred
                    distribution method for Red Hat Developer Hub.
  push              Pushes the already-built dynamic-plugin OCI artifact to the registry.
  tgz               Extracts the plugin tarballs from the OCI artifact via skopeo and
                    writes them to $dynamic_plugins_root_dir/artifacts/.
  backstage-image   Builds the Backstage application Docker image using the Dockerfile at
                    the workspace root and tags it as
                    \$REGISTRY_URL/\$ORG_ID/\$REPO:\$VERSION.
                    Pass --push to also push the image to the registry.
EOF
}

# Prefer podman; fall back to docker.
_pocker="$(command -v podman || command -v docker)"

function _export_plugin {
  local plugin_dir="$1"
  echo "Exporting plugin: $plugin_dir"
  cd "$workspace_dir/$plugin_dir"
  npx @red-hat-developer-hub/cli@latest plugin export \
    --embed-package @red-hat-developer-hub/backstage-plugin-dcm-common
  cd "$workspace_dir"
}

function _package_dynamic_plugins {
  local args=( )
  if [[ "$_pocker" =~ docker$ ]]; then
    args+=( --container-tool docker )
  fi
  npx @red-hat-developer-hub/cli@latest plugin package "${args[@]}" "$@"
}

function clean {
  rm -rf "$dynamic_plugins_root_dir"
  rm -rf "$workspace_dir/dist-types"
  rm -rf "$workspace_dir"/plugins/*/dist-dynamic
  rm -rf "$workspace_dir"/plugins/*/dist
  rm -rf "$workspace_dir"/packages/*/dist
}

function _update_version {
  for dir in "$workspace_dir"/plugins/*/; do
    [[ -d "$dir" ]] || continue
    cd "$dir"
    yarn version "$VERSION" --immediate
    cd - > /dev/null
  done
}

function _assert_version_is_set {
  if [[ -z "$VERSION" ]]; then
    echo "Error: The VERSION environment variable must be provided"
    exit 1
  fi

  if [[ ! ($VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+) ]]; then
    echo "Error: VERSION must follow semver — e.g. 0.1.0 or 1.2.3-rc1"
    exit 2
  fi
}

function _is_prerelease_version {
  # Pre-release versions contain a hyphen suffix (e.g. 0.1.0-rc1, 1.0.0-alpha).
  [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+-[a-zA-Z] ]]
}

function oci {
  _assert_version_is_set
  _update_version

  echo "Installing dependencies..."
  yarn install

  yarn tsc
  yarn build:all

  # Export each plugin as a dynamic plugin, embedding dcm-common so it does
  # not need to be loaded as a separate package at runtime.
  _export_plugin "plugins/dcm"
  _export_plugin "plugins/dcm-backend"

  # Package all exported plugins into a single OCI artifact.
  _package_dynamic_plugins --tag "$REGISTRY_URL/$ORG_ID/$REPO:$VERSION"

  # For pre-release/QE versions restore package.json so version bumps are not
  # committed; for production versions leave them updated for the release commit.
  if _is_prerelease_version; then
    echo "Pre-release version detected ($VERSION). Restoring package.json files..."
    git restore plugins/*/package.json
  else
    echo "Production version detected ($VERSION). Keep package.json files updated."
    echo "Remember to commit: git commit -am 'Release v$VERSION' && git tag v$VERSION"
  fi
}

function push {
  _assert_version_is_set
  echo "Pushing image: $REGISTRY_URL/$ORG_ID/$REPO:$VERSION"
  "$_pocker" push "$REGISTRY_URL/$ORG_ID/$REPO:$VERSION"
}

function tgz {
  local artifact_name="red-hat-developer-hub-backstage-plugin-dcm"

  oci
  skopeo --override-os linux --override-arch amd64 \
    copy "docker://$REGISTRY_URL/$ORG_ID/$REPO:$VERSION" \
    "dir:$dynamic_plugins_root_dir"

  cd "$dynamic_plugins_root_dir"
  local gzip_file
  gzip_file="$(jq -r '.layers[] | select(.mediaType | endswith("+gzip")) | .digest | split(":")[1]' manifest.json)"

  for file in $(ls -1 | grep -v "$gzip_file"); do
    rm -rf "$file"
  done
  tar -vxf "$gzip_file"
  rm index.json "$gzip_file"

  mv "$artifact_name" package
  tar -vczf "$artifact_name.tgz" package
  rm -rf package

  mv "${artifact_name}-backend" package
  tar -vczf "${artifact_name}-backend.tgz" package
  rm -rf package

  local fe_checksum be_checksum
  fe_checksum="sha512-$(openssl dgst -sha512 -binary < "$dynamic_plugins_root_dir/$artifact_name.tgz" | base64)"
  be_checksum="sha512-$(openssl dgst -sha512 -binary < "$dynamic_plugins_root_dir/${artifact_name}-backend.tgz" | base64)"

  cat <<EOF > checksums.txt
$artifact_name.tgz $fe_checksum
${artifact_name}-backend.tgz $be_checksum
EOF

  cd "$workspace_dir"
}

function backstage-image {
  _assert_version_is_set

  local image_tag="$REGISTRY_URL/$ORG_ID/$REPO:$VERSION"
  local do_push=false

  for arg in "${@:1}"; do
    if [[ "$arg" == "--push" ]]; then
      do_push=true
    fi
  done

  # Mount the host's global Yarn cache into the build container so that packages
  # already downloaded locally don't need to be re-fetched from the registry.
  # The cache path is discovered at runtime; if it doesn't exist we skip the mount.
  local yarn_cache_dir
  yarn_cache_dir=$(yarn config get cacheFolder 2>/dev/null || true)

  local volume_args=()
  if [[ -n "$yarn_cache_dir" && -d "$yarn_cache_dir" ]]; then
    echo "Mounting Yarn cache: $yarn_cache_dir -> /root/.yarn/berry/cache (read-only)"
    volume_args=("--volume" "$yarn_cache_dir:/root/.yarn/berry/cache:Z")
  fi

  echo "Building Backstage app image: $image_tag"
  "$_pocker" build \
    "${volume_args[@]+"${volume_args[@]}"}" \
    --tag "$image_tag" \
    --tag "$REGISTRY_URL/$ORG_ID/$REPO:latest" \
    "$workspace_dir"

  if $do_push; then
    echo "Pushing $image_tag"
    "$_pocker" push "$image_tag"
    "$_pocker" push "$REGISTRY_URL/$ORG_ID/$REPO:latest"
  else
    echo "Image built. Run with --push to push to the registry, or use:"
    echo "  $_pocker push $image_tag"
  fi
}

if [[ $# -eq 0 || $1 =~ -h|--help ]]; then
  _usage
else
  command="$1"
  # Prevent calling internal helpers directly (functions starting with _).
  if [[ ! "$command" =~ ^_ ]]; then
    "$command" "${@:2}"
  else
    _usage
  fi
fi
