#!/usr/bin/env bash
# Copyright Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

script_name="${BASH_SOURCE:-$0}"
script_path=$(realpath "$script_name")
script_dir_path=$(dirname "$script_path")
workspace_dir=$(dirname "$script_dir_path")
dynamic_plugins_root_dir="$workspace_dir/dynamic-plugins-root"

REGISTRY_URL="${REGISTRY_URL:-quay.io}"
ORG_ID="${ORG_ID:-dcm-project}"
REPO="${REPO:-dcm-ui-rhdh}"
VERSION="${VERSION:-}"

function _usage {
  cat <<EOF
Usage:
  VERSION=<semver> $script_name
  VERSION=<semver> $script_name [tgz]
  $script_name clean
  $script_name --help

Builds the DCM dynamic-plugin OCI artifact, pushes :\$VERSION, and tags :latest.

Environment variables:
  VERSION         Required. The plugin version; also used to tag the container image.
  REGISTRY_URL    Optional. Container registry URL. Default: quay.io
  ORG_ID          Optional. Organization / namespace in the registry. Default: dcm-project
  REPO            Optional. Repository name. Default: dcm-ui-rhdh

Sub-commands:
  (default)         Builds, pushes :VERSION, and copies the tag to :latest via skopeo.
  clean             Removes directories generated by this script.
  tgz               Extracts the plugin tarballs from the OCI artifact via skopeo and
                    writes them to $dynamic_plugins_root_dir/.
EOF
  return 0
}

# Prefer podman; fall back to docker.
_pocker="$(command -v podman || command -v docker)"

# Path to the rhdh-cli binary, populated by _ensure_rhdh_cli.
_rhdh_cli_bin=""

function _ensure_rhdh_cli {
  # Install the CLI with lifecycle scripts disabled so Sonar does not flag
  # on-demand npx installs that execute package install scripts.
  if [[ -n "$_rhdh_cli_bin" && -x "$_rhdh_cli_bin" ]]; then
    return 0
  fi
  local cli_prefix
  cli_prefix="$(mktemp -d)"
  npm install @red-hat-developer-hub/cli@latest --ignore-scripts --prefix "$cli_prefix"
  _rhdh_cli_bin="$cli_prefix/node_modules/.bin/rhdh-cli"
  if [[ ! -x "$_rhdh_cli_bin" ]]; then
    echo "Error: failed to install rhdh-cli at $_rhdh_cli_bin" >&2
    exit 1
  fi
  return 0
}

function _export_plugin {
  local plugin_dir="$1"
  echo "Exporting plugin: $plugin_dir"
  _ensure_rhdh_cli
  cd "$workspace_dir/$plugin_dir"
  "$_rhdh_cli_bin" plugin export \
    --embed-package @red-hat-developer-hub/backstage-plugin-dcm-common
  cd "$workspace_dir"
  return 0
}

function _package_dynamic_plugins {
  local args=( )
  if [[ "$_pocker" =~ docker$ ]]; then
    args+=( --container-tool docker )
  fi
  _ensure_rhdh_cli
  "$_rhdh_cli_bin" plugin package "${args[@]}" "$@"
  return 0
}

function clean {
  rm -rf "$dynamic_plugins_root_dir"
  rm -rf "$workspace_dir/dist-types"
  rm -rf "$workspace_dir"/plugins/*/dist-dynamic
  rm -rf "$workspace_dir"/plugins/*/dist
  rm -rf "$workspace_dir"/packages/*/dist
  return 0
}

function _update_version {
  for dir in "$workspace_dir"/plugins/*/; do
    [[ -d "$dir" ]] || continue
    cd "$dir"
    yarn version "$VERSION" --immediate
    cd - > /dev/null
  done
  return 0
}

function _assert_version_is_set {
  if [[ -z "$VERSION" ]]; then
    echo "Error: The VERSION environment variable must be provided" >&2
    exit 1
  fi

  if [[ ! ($VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+) ]]; then
    echo "Error: VERSION must follow semver — e.g. 0.1.0 or 1.2.3-rc1" >&2
    exit 2
  fi
  return 0
}

function _is_prerelease_version {
  # Pre-release versions contain a hyphen suffix (e.g. 0.1.0-rc1, 1.0.0-alpha).
  [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+-[a-zA-Z] ]]
  return $?
}

function _build_oci {
  _assert_version_is_set
  _update_version

  echo "Installing dependencies..."
  YARN_ENABLE_SCRIPTS=false yarn install

  yarn tsc
  yarn build:all

  # Export each plugin as a dynamic plugin, embedding dcm-common so it does
  # not need to be loaded as a separate package at runtime.
  _export_plugin "plugins/dcm"
  _export_plugin "plugins/dcm-backend"

  # Package all exported plugins into a single OCI artifact.
  _package_dynamic_plugins --tag "$REGISTRY_URL/$ORG_ID/$REPO:$VERSION"

  # For pre-release/QE versions restore package.json so version bumps are not
  # committed; for production versions leave them updated for the release commit.
  if _is_prerelease_version; then
    echo "Pre-release version detected ($VERSION). Restoring package.json files..."
    git restore plugins/*/package.json
  else
    echo "Production version detected ($VERSION). Keep package.json files updated."
    echo "Remember to commit: git commit -am 'Release v$VERSION' && git tag v$VERSION"
  fi
  return 0
}

function _push {
  _assert_version_is_set
  echo "Pushing image: $REGISTRY_URL/$ORG_ID/$REPO:$VERSION"
  "$_pocker" push "$REGISTRY_URL/$ORG_ID/$REPO:$VERSION"
  return 0
}

function _tag_latest {
  _assert_version_is_set
  echo "Tagging $REGISTRY_URL/$ORG_ID/$REPO:$VERSION as :latest"
  skopeo copy \
    "docker://$REGISTRY_URL/$ORG_ID/$REPO:$VERSION" \
    "docker://$REGISTRY_URL/$ORG_ID/$REPO:latest"
  return 0
}

function build_and_push {
  _build_oci
  _push
  _tag_latest
  return 0
}

function tgz {
  local artifact_name="red-hat-developer-hub-backstage-plugin-dcm"

  build_and_push
  skopeo --override-os linux --override-arch amd64 \
    copy "docker://$REGISTRY_URL/$ORG_ID/$REPO:$VERSION" \
    "dir:$dynamic_plugins_root_dir"

  cd "$dynamic_plugins_root_dir"
  local gzip_file
  gzip_file="$(jq -r '.layers[] | select(.mediaType | endswith("+gzip")) | .digest | split(":")[1]' manifest.json)"

  for file in $(ls -1 | grep -v "$gzip_file"); do
    rm -rf "$file"
  done
  tar -vxf "$gzip_file"
  rm index.json "$gzip_file"

  mv "$artifact_name" package
  tar -vczf "$artifact_name.tgz" package
  rm -rf package

  mv "${artifact_name}-backend" package
  tar -vczf "${artifact_name}-backend.tgz" package
  rm -rf package

  local fe_checksum be_checksum
  fe_checksum="sha512-$(openssl dgst -sha512 -binary < "$dynamic_plugins_root_dir/$artifact_name.tgz" | base64)"
  be_checksum="sha512-$(openssl dgst -sha512 -binary < "$dynamic_plugins_root_dir/${artifact_name}-backend.tgz" | base64)"

  cat <<EOF > checksums.txt
$artifact_name.tgz $fe_checksum
${artifact_name}-backend.tgz $be_checksum
EOF

  cd "$workspace_dir"
  return 0
}

if [[ $# -eq 0 ]]; then
  build_and_push
elif [[ $1 =~ -h|--help ]]; then
  _usage
elif [[ "$1" == "clean" ]]; then
  clean
elif [[ "$1" == "tgz" ]]; then
  tgz
else
  echo "Error: unknown argument '$1'" >&2
  _usage
  exit 1
fi
